name: "Env to JSON"
description: "Convert an Environment File to or from JSON."
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  source:
    description: "Source File Path"
    required: true
  type:
    description: "Output Type"
    required: false
    default: "json"
  dest:
    description: "Output File"
    required: false
  sensitive:
    description: "Sensitive Data"
    required: false
    default: "false"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"

outputs:
  result:
    description: "Conversion Results"

runs:
  using: "node24"
  main: "dist/index.js"
