name: "Env to JSON"
description: "Convert an Environment File to or from JSON."
author: "Shane"
branding:
  icon: "code"
  color: "green"

inputs:
  source-data:
    description: "Source Data or File Path"
    required: true
  source:
    description: "Source Data or File Path"
    deprecationMessage: "Input has changed to: source-type"
  source-type:
    description: "Source Type"
    default: "env"
  type:
    description: "Source Type"
    deprecationMessage: "Input has changed to: source-type"
  output-type:
    description: "Output Type"
  output-file:
    description: "Output File Path"
  dest:
    description: "Output File Path"
    deprecationMessage: "Input has changed to: output-file"
  sensitive:
    description: "Sensitive Data"
    default: "false"
  summary:
    description: "Add Summary to Job"
    default: "true"

outputs:
  result:
    description: "Conversion Results"

runs:
  using: "node24"
  main: "dist/index.js"
