name: "Test"

# actions-up-ignore-file

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: [master]
  pull_request:

env:
  ENV_FILE: .github/test/test.env
  JSON_FILE: .github/test/test.json

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "1: Test: ENV -> JSON"
        id: json
        uses: ./
        with:
          summary: ${{ !github.event.act }}
          source-data: ${{ env.ENV_FILE }}
          #source-type: "env"
          output-file: .github/test/results.json
          #output-type: "json"

      - name: "1: Verify: ENV -> JSON"
        #if: ${{ !github.event.act }}
        run: |
          echo '${{ steps.json.outputs.result }}'
          echo '--------'
          cat .github/test/results.json
          if [ '${{ steps.json.outputs.result }}' != "$(cat .github/test/results.json)" ];then
            echo "JSON Verification Failed: results.json"
            exit 1
          fi

      - name: "2: Test: JSON -> ENV"
        #if: ${{ !github.event.act }}
        id: env
        uses: ./
        with:
          summary: ${{ !github.event.act }}
          source-data: ${{ env.JSON_FILE }}
          source-type: "json"
          output-file: .github/test/results.env
          #output-type: "env"
          sensitive: true

      - name: "2: Verify: JSON -> ENV"
        #if: ${{ !github.event.act }}
        run: |
          echo '${{ steps.env.outputs.result }}'
          echo '--------'
          cat .github/test/results.env
          if [ '${{ steps.env.outputs.result }}' != "$(cat .github/test/results.env)" ];then
            echo "Environment Verification Failed: results.env"
            exit 1
          fi

      #- name: "Schedule Failure Notification"
      #  if: ${{ failure() && github.event_name == 'schedule' }}
      #  uses: sarisia/actions-status-discord@v1
      #  with:
      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
